### PR TITLE
Fix mem leak and simplify code

### PR DESCRIPTION
**Pull request by cokelito1**
fixed two mem leaks and reduced the "similar code" with macros and a class table

### CODE REVIEW

**Comment by mattearly** [comment]
Thank you for your contribution. I'll go about testing and merging in the next build.

**Comment by cokelito1** [comment]
updated with structures for specific attributes of classes on Generic_Character_Class and updated README with color activation for the terminal on windows

**Comment by mattearly** [comment]
finally got some time to test this out! I do appreciate the efforts.

Note 1: Some of these changes are desirable, mainly the reduction in code complexity in the classes, but there does seem to be and issue it introduces. I did find a segmentation fault with these changes, in the character builder. To recreate:
1. Build a New Character
2. Save Current Work
3. View Characters

Note 2: Personally I don't prefer the character class abilities to be separated into structs because of the overlap in some class abilities and if future classes are added from supplemental WotC books, this may create even more overlaps.

Note 3: I was unable to find irrefutable proof of a memory leak, unfortunately (not saying there isn't, still testing, couldn't create any problems with heavy testing in creating and deleting all types of characters). Also, I couldn't get Valgrind memcheck to run due to std::random_device not being supported by Valgrind yet.

**Comment by cokelito1** [comment]
Ok, im going to revert the commit that introduces the separation on of ability into structs, im going to investigate the segfault now, have a nice day

**Comment by cokelito1** [comment]
Ok, i solved the issue, for some reason when i deleted the tmp Generic_Character_Class made a crash on save, in my machine it created a 4GiB file of save when i run it through gdb  ᷅\_(ヅ)_/ ᷄ , Now this branch is a clusterfuck so i created a new branch and i going to make the pull request now for you to test

**Pull request closed without merging**
